export { DidIndyRegistrar } from './did-indy'
export { DidIndyBesuRegistrar } from './did-indybesu'
export { DidKeyRegistrar } from './did-key'
export { DidJwkRegistrar } from './did-jwk'
export { DidHederaRegistrar } from './did-hedera'
