services:
  postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=heka
      - POSTGRES_PASSWORD=heka1
      - POSTGRES_DB=heka-sso-service
  heka-sso-service:
    image: heka-sso-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_VERSION=0.0.1
      - APP_PORT=3005
      - APP_ENABLE_CORS=true
      - LOG_LEVEL=trace
      - LOG_EXCLUDE_URLS=/version,/health
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=heka-sso-service
      - DB_USER=heka
      - DB_PASSWORD=heka1
      - OIDC_ISSUER_URL=http://localhost:3005
      - OIDC_COOKIE_KEYS=dev-only-cookie-key-do-not-use-in-production
      - OIDC_SUB_HMAC_SALT=dev-only-sub-hmac-salt-do-not-use-in-production
      - IDENTITY_SERVICE_BASE_URL=http://localhost:3000
    ports:
      - '3005:3005'
    depends_on:
      - postgres
